### ISSUE TITLE
Help with Look Sync, Make Promise

### ISSUE THREAD

**Issue by swinston100** [isRuslan/learn-generators#31]
Hi @isRuslan 

You were so helpful with my last query that I have another quick on for you,

Here is my code (it works):

``` js
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}

function run (generator) {
  var it = generator(); //create itterator to control generator

  function go(result) { //result is what is yielded by the generator following it.next(), firt time around it is a new Promise

    if (result.done) return result.value; //returns undefined
    //if not done, the promise is pending

    console.log(result);                //{ value: Promise { 'foo' }, done: false }
    console.log(result.value);          //Promise { 'foo' }
    console.log(result.value.then());   //Promise { <pending> }

    result.value.then(fufilled,rejected); //return???

    function fufilled(value) {
      go(it.next(value)); //pass the resolved value back to the run function  - need to return???
    }

    function rejected(error) {
      go(it.throw(error));   //return???
    }

  }
  go(it.next()); //start generator
}

run(function* () {
  try {
    var foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log('Error: ' + e);
  }
});
```

I got stuck for a very long time dealing with the `result`parameter. I thought `result` was a Promise returned by `getFoo()` but `result.then()` did not work.

Only through some logging

``` js
    console.log(result);                //{ value: Promise { 'foo' }, done: false }
    console.log(result.value);          //Promise { 'foo' }
    console.log(result.value.then());   //Promise { <pending> }

```

Did I see that  I needed to do `result.value` to access the Promise.
Can you explain why this is as nowhere in the documentation can I find any references to Promise.value

For example

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

creates a new promise `p1` and then `p1.then()` works as I would expect.

The last thing is why are returns required here in your solution:

``` js
    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
```

I didn't put them in and it works fine, am I asking for trouble ;-)

Thanks so much again for everything!

**Comment by isRuslan** [comment]
Hi @swinston100! 

Let's deep into promise + generators questions.

>  I see that I needed to do result.value to access the Promise.

This is absolutely true.
The `result` argument in example above is result of `it.next()` call and **it.next returns an iterator** which have `{value: VALUE_FROM_YIELD, done: IS_THIS_FINISHED}` semantic - this is very first exercise in `learn-generators`. 
So `result` is not Promise from `getFoo`, it is an iterator from `it.next` which has Promise in `.value` field.

> The last thing is why are returns required here in your solution

This is another truth.
But the `return` requirement exist not due to generators or only in this example. **This is Promise implementation requirement**.

`Promise.prototype.then()` should always return something.

Above example works with no `return` because there is no Promise chain. You can put several `.then` calls following one by another to get sync steps of async operations.
More docs and example in: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

Promises are really helpful with the help of generators, and the deserve separate workshopper.

**Comment by isRuslan** [comment]
@swinston100 if it solves your question, I'll close this.

**Comment by swinston100** [comment]
Hi @isRuslan 

Sorry I didn't see your answer until now.
Almost there... thanks!!!!
The first part is very clear.
The second part is tougher to understand.

I see why

``` js
    function fufilled(value) {
      return go(it.next(value)); //pass the resolved value back to the run function
    }

    function rejected(error) {
      return go(it.throw(error));  
    }
```

would allow hypothetically to add another `then()` as follows:

``` js
result.value.then(fufilled,rejected).then()
```

But i still don't understand why the `return`here is necessary.

``` js
 return result.value.then(fufilled,rejected);
```

**Comment by isRuslan** [comment]
About the second part.

Yes, current implementation of `run` function does not require `return` keyword, this will work:

``` js
 return result.value.then(fufilled,rejected);
```

But still, it is correct to always return something from Promise, due to implementation requirements.

**Comment by swinston100** [comment]
OK many thanks!
